language: haxe

services:
    - redis

install:
  - yes | haxelib install test.hxml
  - yes | haxelib install hxml/test.cpp.hxml

  ## Comment or remove once stable API is reached:
  - yes | haxelib git callnest https://github.com/chfoo/callnest
  - yes | haxelib git commonbox https://github.com/chfoo/commonbox

script:
  - haxe hxml/test.neko.hxml
  - haxe hxml/test.cpp.hxml
  - neko out/neko/test.n
  - ./out/cpp/TestAll-debug
